<?php

use Drupal\coyote_img_desc\Util;
use Drupal\coyote_img_desc\ContentParser;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

function coyote_img_desc_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display): void
{
  $build['#post_render'][] = 'coyote_img_desc_node_view_alter_post_render';
}

function coyote_img_desc_node_view_alter_post_render(string $html, array &$build): string
{
  return ContentParser::replaceImageDescriptions($html, function(string $source): ?string {
    $resource = Util::getImageResourceBySourceUri($source);
    return is_null($resource) ? null : $resource->getCoyoteDescription();
  });
}