coyote_img_desc.settings:
  type: config_object
  label: 'Coyote Image Description settings'
  mapping:
    api_token:
      type: string
      label: 'API Token'
    api_endpoint:
      type: string
      label: 'API Endpoint'
    api_organization:
      type: integer
      label: 'API Organization'
    api_resource_group:
      type: integer
      label: 'API Resource Group'
    disable_coyote_filtering:
      type: boolean
      label: 'Disable Coyote Filtering'
    ignore_coyote_webhook_calls:
      type: boolean
      label: 'Ignore Incoming Coyote Webhook Calls'
    coyote_process_unpublished_nodes:
      type: boolean
      label:  'Disable processing unpublished nodes'
