coyote_img_desc.settings:
  type: config_object
  label: 'Coyote Image Description settings'
  mapping:
    api_token:
      type: string
      label: 'API Token'
    api_endpoint:
      type: string
      label: 'API Endpoint'
    api_organization:
      type: integer
      label: 'API Organization'